name: academic-success
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyter-book
  - jupyterlab
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - numpy
  - ipykernel
